name: socket_io_client_v1
description: Dartlang port of socket.io-client for web, flutter, dartvm to use
version: 1.0.2
homepage: https://www.zkoss.org
repository: https://github.com/rikulo/socket.io-client-dart
issue_tracker: https://github.com/rikulo/socket.io-client-dart/issues
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  socket_io_common_v1:
    git:
      url: git://github.com/azhezzzz/socket_io_common.git
      ref: "socket_io_common_v1"
  js: "^0.6.3"
  logging: "^1.0.1"

dev_dependencies:
  socket_io: any
  build_runner: any
  build_web_compilers: any
